id: IBC25DF2D
legacy_id: P000703
ocr_import_info:
  bdrc_scan_id: W22350
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T23:15:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:25:05.877133+00:00'
last_modified: 2022-09-02 05:25:14.304520
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22350
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22350
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐུ་འབུམ་ཆོས་སྤྱོད་སྐལ་བཟང་ནོར་བུའི་དོ་ཤལ།
statistics:
  ocr_word_mean_confidence_index: 0.7113743069662147
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I1KG10846:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10846
      total_pages: 266
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10846.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7113743069662147
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
