id: IBC25DF2D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:17:24+00:00'
last_modified: '2022-06-07T12:42:10.239851+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22350
  title: སྐུ་འབུམ་ཆོས་སྤྱོད་སྐལ་བཟང་ནོར་བུའི་དོ་ཤལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C1CF:
      image_group_id: I1KG10846
      title: ''
      total_pages: 266
      order: 1
      base_file: C1CF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
