id: P000703
initial_creation_type: ocr
source_metadata:
  id: bdr:W22350
  title: སྐུ་འབུམ་ཆོས་སྤྱོད་སྐལ་བཟང་ནོར་བུའི་དོ་ཤལ།
  author: ''
  volumes:
    538776eb525045dda45e033748967cac:
      image_group_id: I1KG10846
      title: ''
      volume_number: 1
      total_pages: 266
