id: P000703
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:56.467372
source_metadata:
  id: bdr:W22350
  title: སྐུ་འབུམ་ཆོས་སྤྱོད་སྐལ་བཟང་ནོར་བུའི་དོ་ཤལ།
  author: ''
  volumes:
    538776eb525045dda45e033748967cac:
      image_group_id: I1KG10846
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
